### ISSUE TITLE
Helm chart should read image registry name from global.imageRegistry variable

### ISSUE THREAD

**Issue by rbcek** [openebs/dynamic-localpv-provisioner#203]
**Describe the problem/challenge you have**
To use `my-image-registry` as image registry I have to specify for each setup:
```
localpv:
  image:
    registry: "my-image-registry/"
helperPod:
  image:
    registry: "my-image-registry/"
```

**Describe the solution you'd like**
Usage of  `global.imageRegistry`, which is commonly used would be perfect (without need to append '/' at the end):
```
global:
  imageRegistry: "my-image-registry"
```

**Anything else you would like to add:**
Probably this value should be used as default. Values provided as  `localpv.image.registry` or `helperPod.image.registry` should overwrite default value.
