### ISSUE TITLE
Include BlockDevice driveType as selector within cas.openebs.io/config

### ISSUE THREAD

**Issue by deeluk** [openebs/dynamic-localpv-provisioner#35]
**Describe the problem/challenge you have**
I would like to be able to separate device types into separate storage classes so that workloads can control which device type will provide storage for their workload by specifying the appropriate storage class.

**Describe the solution you'd like**
Allow the StorageClass annotation cas.openebs.io/config to filter on the driveType details coming from Node Device Manager via the BlockDevice CR.  For instance:
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-device
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: DeviceType
        value: SSD
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
Where the DeviceType value would be HDD, SSD, NVMe, etc.  Similar to the mechanism described in the docs to filter devices based on a tag like `openebs.io/block-device-tag=mongo`.

**Anything else you would like to add:**
Slack discussion: https://kubernetes.slack.com/archives/CUAKPFU78/p1615567766054600

**Environment:**
- OpenEBS version 2.6.0
- Kubernetes version 1.17.0
- Cloud provider or hardware configuration: HP Z8 G4
- OS (e.g: `cat /etc/os-release`): ubuntu 18.04
- kernel (e.g: `uname -a`): 5.3.0-28-generic

**Comment by akhilerm** [comment]
@deeluk Can you check if https://github.com/openebs/device-localpv, solves your problem. Its a CSI driver for directly accessing the disk.

**Comment by deeluk** [comment]
@akhilerm I'm not sure what you mean.  Does device-localpv allow you to select devices based on the drive type?

**Comment by RealHarshThakur** [comment]
I think one way to solve this would be to label block devices with the drive type without human intervention as opposed to having a new field to specify drive type in storage class but this requires localpv to support multiple tags. WDYT? @akhilerm

**Comment by akhilerm** [comment]
>  Does device-localpv allow you to select devices based on the drive type?

@deeluk Its doesn't directly allow you to select based on drive type. But it can be done by preselecting the devices which you want to use, So here instead of tagging you will be using a meta partition on the disk.

**Comment by deeluk** [comment]
@akhilerm so you would have to perform some operation on each drive you want to target (the meta partition), then you can use that as a filter in the StorageClass?  Not ideal.  In my mind, this was a mechanism that allows an administrator to selectively filter devices without having to reach out and touch each one before provisioning.  If an admin has to touch each device to keep it in or out of a selection set, then we could just use labels.

**Comment by RealHarshThakur** [comment]
Yeah ,  cloud providers also offer drive type as a parameter: https://github.com/kubernetes-sigs/gcp-compute-persistent-disk-csi-driver#createvolume-parameters

**Comment by akhilerm** [comment]
@deeluk We are exploring on another solution, where a configuration will be provided to NDM (may be as part of ConfigMap). This configuration will have specification on auto tagging disks with certain details. for eg: if the disk is HDD, the blockdevice resource will be tagged with `openebs.io/block-device-tag=HDD`. Thus, manually labelling each device can be avoided. Once the resources are automatically tagged, you can pass that information in the storage and use it. 

What do you think of this approach?

**Comment by RealHarshThakur** [comment]
Another idea to solve this problem for both CSI and Non-CSI is if we import NDM as a library to detect the drive type. The drive type can then be provided in Storage Class as a parameter. CSI/Non-CSI driver using the NDM library picks a disk of desired drive type and can then create a PV. (What happens when there's more than one disk eligible, etc are some questions we need to think about)

I am not sure how easy it would be to create  a library out of NDM to use in such a way though ....but the benefit of solving this for CSI based drivers too would be a huge win.

**Comment by deeluk** [comment]
> @deeluk We are exploring on another solution, where a configuration will be provided to NDM (may be as part of ConfigMap). This configuration will have specification on auto tagging disks with certain details. for eg: if the disk is HDD, the blockdevice resource will be tagged with `openebs.io/block-device-tag=HDD`. Thus, manually labelling each device can be avoided. Once the resources are automatically tagged, you can pass that information in the storage and use it.
> 
> What do you think of this approach?

@akhilerm sounds like a good solution to me.

**Comment by kmova** [comment]
Ability to attach device attributes and topology details to block devices seem to provide the maximum flexibility in how BDCs can claim devices. 

Once the above feature is available in NDM (Issue 615), then the Storage Class configure can be modified to specify one or more selectors as follows:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-device
  annotations:
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
         value: "device"
      - name: BlockDeviceSelectors
         value: |-
           ndm.io/drive-type: "SSD"
           ndm.io/filesystem-type: "none"
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
```
